"""
cGAN + ATCN augmentation on C-MAPSS (FD001–FD004)

Goal:
  Scenario 3 — show that ATCN can still perform well when trained on a mix of
  limited real data + synthetic data generated by a lightweight conditional GAN.

Pipeline:
  1) Load FD00X and preprocess (RUL labels + curated sensors)
  2) Simulate LOW-DATA scenario (subset of units, e.g. 30%)
  3) Scale features on small-train only (MinMax [-1,1])
  4) Train conditional GAN (G, D) on (X_small_train_scaled, y_small_train)
  5) Generate synthetic sequences conditioned on RUL
  6) Train:
       - ATCN_real_small         on small real only
       - ATCN_real_plus_syn      on real small + synthetic
  7) Evaluate both on REAL test set
  8) Save models, CSV summary, and plots:
       - real vs synthetic sequences (few sensors)
       - prediction vs truth
       - scatter + residuals

Expected layout:
  <project>/
    gan_atcn_augmentation.py
    data/
      train_FD001.txt
      test_FD001.txt
      RUL_FD001.txt
      (and optionally FD002–FD004)
"""

# ===================== 1. IMPORTS & GLOBAL CONFIG =====================

import os
import random

import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# ----- Dataset selector -----
# Change this to "FD001", "FD002", "FD003", or "FD004"
FDX = "FD004"

# ----- Paths -----
DATA_PATH = "./data"
RESULTS_ROOT = "./results_gan_atcn"
RESULTS_DIR = os.path.join(RESULTS_ROOT, FDX)
os.makedirs(RESULTS_DIR, exist_ok=True)

# ----- Core config -----
SEQ_LEN = 50
RUL_CAP = 125

# GAN config
NOISE_DIM = 32
GAN_EPOCHS = 40
GAN_BATCH = 64

# ATCN config
ATCN_DMODEL = 64
ATCN_FILTERS = 64
ATCN_EPOCHS = 30
ATCN_BATCH = 256

# Low-data scenario config
LOW_DATA_FRACTION_UNITS = 0.3   # use 30% of units to simulate "limited data"
VAL_FRACTION_UNITS = 0.2        # of those low-data units, 20% used for validation

# Debug toggle
DEBUG = False  # set True for super quick smoke test

if DEBUG:
    GAN_EPOCHS = 5
    GAN_BATCH = 32
    ATCN_EPOCHS = 5
    ATCN_BATCH = 64
    print(f"\n⚡ DEBUG MODE: FD={FDX}, GAN_EPOCHS={GAN_EPOCHS}, ATCN_EPOCHS={ATCN_EPOCHS}\n")
else:
    print(f"\n🚀 FULL GAN+ATCN RUN: FD={FDX}, LOW_DATA_FRACTION={LOW_DATA_FRACTION_UNITS}\n")


# ===================== 2. REPRODUCIBILITY & METRICS =====================

def set_all_seeds(seed: int = 42):
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)


def nasa_score_func(y_true, y_pred):
    """
    NASA scoring (early predictions cheaper than late).
    d = y_pred - y_true
      if d < 0 (predict smaller RUL = early):  exp(-d/13) - 1
      else (predict larger RUL = late):        exp(d/10) - 1
    """
    d = y_pred - y_true
    scores = np.where(d < 0,
                      np.exp(-d / 13.0) - 1.0,
                      np.exp(d / 10.0) - 1.0)
    return float(np.sum(scores))


def evaluate_metrics(y_true, y_pred):
    y_true = y_true.flatten().astype(np.float32)
    y_pred = y_pred.flatten().astype(np.float32)
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    nasa = nasa_score_func(y_true, y_pred)
    return rmse, nasa


class TrainingTracker(keras.callbacks.Callback):
    """Pretty training log for ATCN."""
    def on_train_begin(self, logs=None):
        print("\n🚀 ATCN training started")

    def on_epoch_begin(self, epoch, logs=None):
        print(f"\n— Epoch {epoch + 1}/{self.params['epochs']} —")

    def on_epoch_end(self, epoch, logs=None):
        loss = logs.get("loss", float("nan"))
        val_loss = logs.get("val_loss", float("nan"))
        try:
            lr = float(tf.keras.backend.get_value(self.model.optimizer.learning_rate))
        except Exception:
            lr = float("nan")
        print(f"   loss={loss:.5f} | val_loss={val_loss:.5f} | lr={lr:.6f}")

    def on_train_end(self, logs=None):
        print("🏁 ATCN training finished.\n")


# ===================== 3. DATA LOADING & PREPROCESSING =====================

def load_fd(data_path=DATA_PATH, fd=FDX):
    """Load FDxxx train/test/RUL with standard C-MAPSS columns."""
    cols = (
        ["unit_nr", "cycle"]
        + [f"setting_{i}" for i in range(1, 4)]
        + [f"sensor_{i}" for i in range(1, 22)]
    )

    train_file = os.path.join(data_path, f"train_{fd}.txt")
    test_file  = os.path.join(data_path, f"test_{fd}.txt")
    rul_file   = os.path.join(data_path, f"RUL_{fd}.txt")

    if not (os.path.exists(train_file) and os.path.exists(test_file) and os.path.exists(rul_file)):
        raise FileNotFoundError(
            f"{fd} files not found under ./data.\n"
            f"Expected train_{fd}.txt, test_{fd}.txt, RUL_{fd}.txt"
        )

    train_df = pd.read_csv(train_file, sep=r"\s+", header=None, names=cols)
    test_df  = pd.read_csv(test_file,  sep=r"\s+", header=None, names=cols)
    rul_df   = pd.read_csv(rul_file,   sep=r"\s+", header=None, names=["RUL"])
    return train_df, test_df, rul_df


def add_rul(train_df, cap=RUL_CAP):
    """Add piecewise-capped RUL for each training unit."""
    df = train_df.copy()
    max_cycles = df.groupby("unit_nr")["cycle"].max()
    df = df.merge(max_cycles.to_frame("max_cycle"), left_on="unit_nr", right_index=True)
    df["RUL"] = (df["max_cycle"] - df["cycle"]).clip(upper=cap).astype(np.float32)
    df.drop(columns=["max_cycle"], inplace=True)
    return df


def get_useful_sensors(train_df, fd=FDX, threshold=1e-6):
    """Curated sensor selection for FD001–FD004 + variance filtering."""
    curated_sets = {
        "FD001": [
            "sensor_2","sensor_3","sensor_4",
            "sensor_7","sensor_8","sensor_9",
            "sensor_11","sensor_12","sensor_13","sensor_14"
        ],
        "FD002": [
            "sensor_1","sensor_2","sensor_3","sensor_4",
            "sensor_7","sensor_8","sensor_9","sensor_10",
            "sensor_11","sensor_12","sensor_13","sensor_14",
            "sensor_15","sensor_17","sensor_20","sensor_21"
        ],
        "FD003": [
            "sensor_1","sensor_2","sensor_3","sensor_4",
            "sensor_7","sensor_8","sensor_9","sensor_11",
            "sensor_12","sensor_13","sensor_14",
            "sensor_17","sensor_20","sensor_21"
        ],
        "FD004": [
            "sensor_1","sensor_2","sensor_3","sensor_4",
            "sensor_6","sensor_7","sensor_8","sensor_9",
            "sensor_10","sensor_11","sensor_12","sensor_13",
            "sensor_14","sensor_15","sensor_17","sensor_20",
            "sensor_21"
        ]
    }

    all_sensor_cols = [c for c in train_df.columns if c.startswith("sensor_")]
    variances = train_df[all_sensor_cols].var()
    useful = variances[variances > threshold].index.tolist()
    print("\n📌 Sensors with variance > threshold:")
    print(useful)

    if fd in curated_sets:
        curated = curated_sets[fd]
        features = [s for s in curated if s in useful]
        print(f"\n📌 {fd} curated sensors (after variance filtering):")
        print(features)
    else:
        print(f"\n⚠ Unknown FD '{fd}', using variance-based sensors only.")
        features = useful

    return features


def create_windows_train(df, seq_len, feature_cols):
    """Create sliding windows and labels for train/val."""
    X_list, y_list, units_list = [], [], []
    for u in df["unit_nr"].unique():
        u_df = df[df["unit_nr"] == u].sort_values("cycle")
        values = u_df[feature_cols].values.astype(np.float32)
        rul    = u_df["RUL"].values.astype(np.float32)

        if len(values) < seq_len:
            continue

        for i in range(len(values) - seq_len + 1):
            X_list.append(values[i:i + seq_len])
            y_list.append(rul[i + seq_len - 1])
            units_list.append(u)

    X = np.array(X_list, dtype=np.float32)
    y = np.array(y_list, dtype=np.float32)
    units = np.array(units_list)
    return X, y, units


def create_windows_test(test_df, rul_df, seq_len, feature_cols):
    """One window per test unit: last seq_len cycles, left-padded if needed."""
    X_list = []
    for u in test_df["unit_nr"].unique():
        u_df = test_df[test_df["unit_nr"] == u].sort_values("cycle")
        values = u_df[feature_cols].values.astype(np.float32)

        if len(values) >= seq_len:
            w = values[-seq_len:]
        else:
            pad_len = seq_len - len(values)
            pad = np.repeat(values[:1], pad_len, axis=0)
            w = np.vstack([pad, values])
        X_list.append(w)

    X_test = np.array(X_list, dtype=np.float32)
    y_test = rul_df["RUL"].values.astype(np.float32)
    return X_test, y_test


def preprocess_fd(fd=FDX):
    """
    Load FDxxx, assign RUL, select sensors, and build base windows.
    Scaling is done later on the LOW-DATA split.
    """
    train_df, test_df, rul_df = load_fd(DATA_PATH, fd=fd)
    train_df = add_rul(train_df, cap=RUL_CAP)
    feature_cols = get_useful_sensors(train_df, fd=fd)

    print(f"\n=== PREPROCESSING {fd} ===")
    print("Using features:", feature_cols)

    X_all, y_all, units_all = create_windows_train(train_df, SEQ_LEN, feature_cols)
    X_test, y_test = create_windows_test(test_df, rul_df, SEQ_LEN, feature_cols)

    print(f"Train windows: {X_all.shape}, Test windows: {X_test.shape}")
    return train_df, X_all, y_all, units_all, X_test, y_test, feature_cols


def make_low_data_split(X_all, y_all, units_all,
                        frac_units=LOW_DATA_FRACTION_UNITS,
                        val_frac_units=VAL_FRACTION_UNITS,
                        seed=42):
    """
    Simulate low-data scenario:
      - pick subset of units (fraction of all units)
      - within those, choose some units for validation
    """
    rng = np.random.RandomState(seed)
    unique_units = np.unique(units_all)

    n_low = max(1, int(np.ceil(frac_units * len(unique_units))))
    low_units = rng.choice(unique_units, size=n_low, replace=False)

    mask_low = np.isin(units_all, low_units)
    X_low = X_all[mask_low]
    y_low = y_all[mask_low]
    units_low = units_all[mask_low]

    unique_low_units = np.unique(units_low)
    n_val = max(1, int(np.ceil(val_frac_units * len(unique_low_units))))
    val_units = rng.choice(unique_low_units, size=n_val, replace=False)
    train_units = np.array([u for u in unique_low_units if u not in val_units])

    train_mask = np.isin(units_low, train_units)
    val_mask   = np.isin(units_low, val_units)

    X_tr = X_low[train_mask]
    y_tr = y_low[train_mask]
    X_val = X_low[val_mask]
    y_val = y_low[val_mask]

    print(f"\n📉 LOW-DATA SCENARIO:")
    print(f"  total units: {len(unique_units)}")
    print(f"  low-data units: {len(low_units)} "
          f"(train={len(train_units)}, val={len(val_units)})")
    print(f"  X_tr: {X_tr.shape}, X_val: {X_val.shape}")

    return X_tr, y_tr, X_val, y_val


# ===================== 4. ATCN MODEL =====================

class ISABlock(layers.Layer):
    """Improved self-attention block (simple version)."""
    def __init__(self, d=64, heads=2):
        super().__init__()
        self.q = layers.Conv1D(d, 3, padding="same")
        self.k = layers.Conv1D(d, 3, padding="same")
        self.v = layers.Conv1D(d, 3, padding="same")
        self.mha = layers.MultiHeadAttention(heads, key_dim=d // heads)
        self.n1 = layers.LayerNormalization()
        self.ff = keras.Sequential([
            layers.Dense(d * 2, activation="relu"),
            layers.Dense(d)
        ])
        self.n2 = layers.LayerNormalization()

    def call(self, x):
        q, k, v = self.q(x), self.k(x), self.v(x)
        att = self.mha(q, k, v)
        x1 = self.n1(x + att)
        ff = self.ff(x1)
        return self.n2(x1 + ff)


class TCNBlock(layers.Layer):
    def __init__(self, f=64, k=3, d=1):
        super().__init__()
        self.c1 = layers.Conv1D(f, k, padding="causal",
                                dilation_rate=d, activation="relu")
        self.c2 = layers.Conv1D(f, k, padding="causal",
                                dilation_rate=d, activation="relu")
        self.s  = layers.Conv1D(f, 1)

    def call(self, x):
        y = self.c1(x)
        y = self.c2(y)
        return y + self.s(x)


def se_block(x):
    f = x.shape[-1]
    s = layers.GlobalAveragePooling1D()(x)
    s = layers.Dense(max(1, f // 8), activation="relu")(s)
    s = layers.Dense(f, activation="sigmoid")(s)
    s = layers.Reshape((1, f))(s)
    return layers.Multiply()([x, s])


def build_atcn_model(input_shape):
    """
    ATCN:
      - Dense projection to d_model
      - ISA (improved self-attention)
      - 4× TCN blocks with dilations [1,2,4,8]
      - SE channel attention
      - GAP + dense head
    """
    inp = layers.Input(shape=input_shape)
    x = layers.Dense(ATCN_DMODEL)(inp)
    x = ISABlock(ATCN_DMODEL, 2)(x)
    for d in [1, 2, 4, 8]:
        x = TCNBlock(ATCN_FILTERS, 3, d)(x)
    x = se_block(x)
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dense(64, activation="relu")(x)
    out = layers.Dense(1)(x)
    model = keras.Model(inp, out, name="ATCN")
    return model


def train_atcn(X_tr, y_tr, X_val, y_val, X_test, y_test, tag: str):
    """
    Train ATCN and evaluate on real test set.
    Saves model as atcn_{tag}_{FDX}.h5
    """
    model = build_atcn_model((SEQ_LEN, X_tr.shape[-1]))
    model.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss=keras.losses.Huber(delta=5.0)
    )

    ckpt_path = os.path.join(RESULTS_DIR, f"atcn_{tag}_{FDX}.h5")

    callbacks = [
        TrainingTracker(),
        keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=8,
            restore_best_weights=True
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=4,
            min_lr=1e-6
        ),
        keras.callbacks.ModelCheckpoint(
            ckpt_path,
            monitor="val_loss",
            save_best_only=True,
            save_weights_only=False
        )
    ]

    history = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=ATCN_EPOCHS,
        batch_size=ATCN_BATCH,
        verbose=0,
        callbacks=callbacks
    )

    y_pred = model.predict(X_test, batch_size=ATCN_BATCH, verbose=0).flatten()
    rmse, nasa = evaluate_metrics(y_test, y_pred)

    print(f"\n✅ ATCN ({tag}) → Test RMSE={rmse:.3f}, NASA={nasa:.1f}")
    print(f"   Saved model → {ckpt_path}")

    return model, history, y_pred, rmse, nasa


# ===================== 5. CONDITIONAL GAN (cGAN) =====================

def build_generator(seq_len, n_features, noise_dim=NOISE_DIM):
    """
    Conditional generator G(z, y) → sequence (seq_len, n_features)
    Condition is scalar RUL (unscaled).
    Data is expected to be scaled to [-1,1], so we use tanh at the end.
    """
    z_in = layers.Input(shape=(noise_dim,), name="z_input")
    y_in = layers.Input(shape=(1,), name="y_input")

    x = layers.Concatenate()([z_in, y_in])           # (batch, noise_dim+1)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(seq_len * 64, activation="relu")(x)
    x = layers.Reshape((seq_len, 64))(x)

    y_rep = layers.RepeatVector(seq_len)(y_in)       # (batch, seq_len, 1)
    x = layers.Concatenate(axis=-1)([x, y_rep])      # (batch, seq_len, 65)

    x = layers.Conv1D(64, 3, padding="same", activation="relu")(x)
    x = layers.Conv1D(32, 3, padding="same", activation="relu")(x)

    out = layers.Conv1D(n_features, 1, padding="same", activation="tanh")(x)

    model = keras.Model([z_in, y_in], out, name="Generator")
    return model


def build_discriminator(seq_len, n_features):
    """
    Conditional discriminator D(x, y) → probability(real)
    """
    x_in = layers.Input(shape=(seq_len, n_features), name="x_input")
    y_in = layers.Input(shape=(1,), name="y_input")

    y_rep = layers.RepeatVector(seq_len)(y_in)
    d = layers.Concatenate(axis=-1)([x_in, y_rep])   # (batch, seq_len, n_features+1)

    d = layers.Conv1D(64, 3, padding="same", activation="relu")(d)
    d = layers.Conv1D(64, 3, padding="same", activation="relu")(d)
    d = layers.GlobalAveragePooling1D()(d)
    d = layers.Dense(64, activation="relu")(d)
    out = layers.Dense(1, activation="sigmoid")(d)

    model = keras.Model([x_in, y_in], out, name="Discriminator")
    return model


def train_gan(generator, discriminator, X_train, y_train,
              epochs=GAN_EPOCHS,
              batch_size=GAN_BATCH,
              noise_dim=NOISE_DIM):
    """
    Simple conditional GAN training loop.
    X_train: scaled to [-1,1], shape (N, seq_len, n_features)
    y_train: original RUL labels, shape (N,)
    """
    bce = keras.losses.BinaryCrossentropy(from_logits=False)
    g_opt = keras.optimizers.Adam(1e-4)
    d_opt = keras.optimizers.Adam(1e-4)

    dataset = tf.data.Dataset.from_tensor_slices(
        (X_train.astype("float32"), y_train.astype("float32"))
    ).shuffle(buffer_size=len(X_train)).batch(batch_size, drop_remainder=True)

    @tf.function
    def train_step(real_x, real_y):
        # real_y shape: (batch,), we need (batch,1)
        real_y_exp = tf.reshape(real_y, (-1, 1))

        # ----------------- Train Discriminator -----------------
        noise = tf.random.normal(shape=(tf.shape(real_x)[0], noise_dim))
        with tf.GradientTape() as d_tape:
            fake_x = generator([noise, real_y_exp], training=True)

            real_logits = discriminator([real_x, real_y_exp], training=True)
            fake_logits = discriminator([fake_x, real_y_exp], training=True)

            d_loss_real = bce(tf.ones_like(real_logits), real_logits)
            d_loss_fake = bce(tf.zeros_like(fake_logits), fake_logits)
            d_loss = d_loss_real + d_loss_fake

        d_grads = d_tape.gradient(d_loss, discriminator.trainable_variables)
        d_opt.apply_gradients(zip(d_grads, discriminator.trainable_variables))

        # ----------------- Train Generator -----------------
        noise = tf.random.normal(shape=(tf.shape(real_x)[0], noise_dim))
        with tf.GradientTape() as g_tape:
            fake_x = generator([noise, real_y_exp], training=True)
            fake_logits = discriminator([fake_x, real_y_exp], training=True)
            g_loss = bce(tf.ones_like(fake_logits), fake_logits)

        g_grads = g_tape.gradient(g_loss, generator.trainable_variables)
        g_opt.apply_gradients(zip(g_grads, generator.trainable_variables))

        return d_loss, g_loss

    print("\n🎭 Training conditional GAN (Generator + Discriminator)")
    for epoch in range(epochs):
        d_losses, g_losses = [], []
        for real_x_batch, real_y_batch in dataset:
            d_loss, g_loss = train_step(real_x_batch, real_y_batch)
            d_losses.append(d_loss.numpy())
            g_losses.append(g_loss.numpy())
        print(f"Epoch {epoch+1}/{epochs} | D_loss={np.mean(d_losses):.4f} | "
              f"G_loss={np.mean(g_losses):.4f}")

    return generator, discriminator


def generate_synthetic_sequences(generator, y_train, n_samples, noise_dim=NOISE_DIM, batch_size=128):
    """
    Generate synthetic sequences conditioned on RUL labels.
    We re-use y_train as conditioning labels.
    """
    n_train = len(y_train)
    idx = np.random.randint(0, n_train, size=n_samples)
    y_cond = y_train[idx].astype(np.float32).reshape(-1, 1)

    synth_list = []
    for i in range(0, n_samples, batch_size):
        y_batch = y_cond[i:i+batch_size]
        z_batch = np.random.normal(size=(len(y_batch), noise_dim)).astype(np.float32)
        x_batch = generator.predict([z_batch, y_batch], verbose=0)
        synth_list.append(x_batch)

    X_syn = np.concatenate(synth_list, axis=0)
    y_syn = y_cond.flatten().astype(np.float32)
    return X_syn, y_syn


# ===================== 6. PLOTTING HELPERS =====================

def plot_real_vs_synth(X_real, X_syn, feature_cols, out_path, n_sensors=3):
    """
    Compare real vs synthetic trajectories for a few sensors.
    """
    plt.figure(figsize=(10, 4 * n_sensors))

    idx = np.random.randint(0, X_real.shape[0])
    real_seq = X_real[idx]
    syn_seq  = X_syn[idx]

    timesteps = np.arange(real_seq.shape[0])
    num_plots = min(n_sensors, real_seq.shape[1])

    for i in range(num_plots):
        plt.subplot(num_plots, 1, i+1)
        plt.plot(timesteps, real_seq[:, i], label="Real", linewidth=2)
        plt.plot(timesteps, syn_seq[:, i], label="Synthetic", linestyle="--")
        sensor_name = feature_cols[i] if i < len(feature_cols) else f"sensor_{i+1}"
        plt.title(f"Real vs Synthetic – {sensor_name}")
        plt.xlabel("Time step in window")
        plt.ylabel("Scaled value")
        plt.legend()

    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()
    print(f"[Saved] {out_path}")


def plot_pred_vs_true(y_true, preds_dict, out_path, fd=FDX):
    plt.figure(figsize=(10, 4))
    plt.plot(y_true, label="True", linewidth=2)
    for name, p in preds_dict.items():
        plt.plot(p, label=name, linestyle="--")
    plt.xlabel("Test engine index")
    plt.ylabel("RUL")
    plt.title(f"Prediction vs True RUL – {fd}")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()
    print(f"[Saved] {out_path}")


def plot_scatter_multi(y_true, preds_dict, out_path, fd=FDX):
    plt.figure(figsize=(6, 6))
    mn, mx = y_true.min(), y_true.max()
    for name, p in preds_dict.items():
        plt.scatter(y_true, p, alpha=0.5, label=name)
    plt.plot([mn, mx], [mn, mx], "k--", label="ideal")
    plt.xlabel("True RUL")
    plt.ylabel("Predicted RUL")
    plt.title(f"Pred vs True scatter – {fd}")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()
    print(f"[Saved] {out_path}")


def plot_residuals_multi(y_true, preds_dict, out_path, fd=FDX):
    plt.figure(figsize=(10, 4))
    for name, p in preds_dict.items():
        r = p - y_true
        plt.scatter(y_true, r, alpha=0.5, label=name)
    plt.axhline(0, color="k")
    plt.xlabel("True RUL")
    plt.ylabel("Residual (pred - true)")
    plt.title(f"Residuals vs True RUL – {fd}")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()
    print(f"[Saved] {out_path}")


# ===================== 7. MAIN PIPELINE =====================

def main():
    set_all_seeds(42)
    print(f"\n==== cGAN + ATCN on {FDX} ====\n")

    # 1) Base preprocessing
    train_df, X_all, y_all, units_all, X_test, y_test, feat_cols = preprocess_fd(FDX)
    n_features = X_all.shape[-1]

    # 2) Low-data split (unit-wise)
    X_tr_small, y_tr_small, X_val_small, y_val_small = make_low_data_split(
        X_all, y_all, units_all,
        frac_units=LOW_DATA_FRACTION_UNITS,
        val_frac_units=VAL_FRACTION_UNITS,
        seed=42
    )

    # 3) Scaling (fit only on small-train)
    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaler.fit(X_tr_small.reshape(-1, n_features))

    X_tr_small_scaled = scaler.transform(X_tr_small.reshape(-1, n_features)).reshape(X_tr_small.shape)
    X_val_small_scaled = scaler.transform(X_val_small.reshape(-1, n_features)).reshape(X_val_small.shape)
    X_test_scaled = scaler.transform(X_test.reshape(-1, n_features)).reshape(X_test.shape)

    # 4) Build and train conditional GAN on (X_tr_small_scaled, y_tr_small)
    gen = build_generator(SEQ_LEN, n_features, noise_dim=NOISE_DIM)
    disc = build_discriminator(SEQ_LEN, n_features)

    gen, disc = train_gan(
        gen, disc,
        X_tr_small_scaled, y_tr_small,
        epochs=GAN_EPOCHS,
        batch_size=GAN_BATCH,
        noise_dim=NOISE_DIM
    )

    # Save GAN models
    gen_path  = os.path.join(RESULTS_DIR, f"generator_{FDX}.h5")
    disc_path = os.path.join(RESULTS_DIR, f"discriminator_{FDX}.h5")
    gen.save(gen_path)
    disc.save(disc_path)
    print(f"\n💾 Saved GAN models → {gen_path}, {disc_path}")

    # 5) Generate synthetic sequences (same size as small train)
    n_synth = X_tr_small_scaled.shape[0]
    X_syn_scaled, y_syn = generate_synthetic_sequences(
        gen, y_tr_small, n_samples=n_synth,
        noise_dim=NOISE_DIM, batch_size=GAN_BATCH
    )
    print(f"\n🧬 Generated synthetic sequences: {X_syn_scaled.shape}")

    # 6) Train ATCN on REAL SMALL ONLY
    print("\n========== ATCN on REAL SMALL ==========\n")
    atcn_real_small, hist_real_small, y_pred_real_small, rmse_real_small, nasa_real_small = train_atcn(
        X_tr_small_scaled, y_tr_small,
        X_val_small_scaled, y_val_small,
        X_test_scaled, y_test,
        tag="real_small"
    )

    # 7) Train ATCN on REAL SMALL + SYNTHETIC
    print("\n========== ATCN on REAL + SYNTHETIC ==========\n")
    X_tr_comb = np.concatenate([X_tr_small_scaled, X_syn_scaled], axis=0)
    y_tr_comb = np.concatenate([y_tr_small,       y_syn],        axis=0)

    atcn_real_syn, hist_real_syn, y_pred_real_syn, rmse_real_syn, nasa_real_syn = train_atcn(
        X_tr_comb, y_tr_comb,
        X_val_small_scaled, y_val_small,
        X_test_scaled, y_test,
        tag="real_plus_syn"
    )

    # 8) Real vs Synthetic sample trajectories
    real_vs_syn_path = os.path.join(RESULTS_DIR, "real_vs_synthetic_sequences.png")
    plot_real_vs_synth(
        X_tr_small_scaled,
        X_syn_scaled,
        feat_cols,
        real_vs_syn_path,
        n_sensors=min(3, len(feat_cols))
    )

    # 9) Prediction comparison plots on real test set
    preds_dict = {
        "ATCN_real_small": y_pred_real_small,
        "ATCN_real_plus_syn": y_pred_real_syn
    }

    pred_plot_path = os.path.join(RESULTS_DIR, "pred_vs_true_atcn_real_vs_syn.png")
    plot_pred_vs_true(y_test, preds_dict, pred_plot_path, fd=FDX)

    scatter_path = os.path.join(RESULTS_DIR, "scatter_atcn_real_vs_syn.png")
    plot_scatter_multi(y_test, preds_dict, scatter_path, fd=FDX)

    resid_path = os.path.join(RESULTS_DIR, "residuals_atcn_real_vs_syn.png")
    plot_residuals_multi(y_test, preds_dict, resid_path, fd=FDX)

    # 10) Save summary CSV
    summary_df = pd.DataFrame([
        {
            "FD": FDX,
            "model": "ATCN_real_small",
            "train_data": "real_small",
            "test_RMSE": rmse_real_small,
            "test_NASA": nasa_real_small
        },
        {
            "FD": FDX,
            "model": "ATCN_real_plus_syn",
            "train_data": "real_small + synthetic",
            "test_RMSE": rmse_real_syn,
            "test_NASA": nasa_real_syn
        }
    ])

    summary_path = os.path.join(RESULTS_DIR, f"{FDX.lower()}_gan_atcn_summary.csv")
    summary_df.to_csv(summary_path, index=False)
    print(f"\n📄 Saved summary → {summary_path}")
    print("\n=== FINAL SUMMARY ===")
    print(summary_df)

    print("\n--- GAN + ATCN PIPELINE COMPLETE ---")
    print(f"Results folder: {RESULTS_DIR}\n")


if __name__ == "__main__":
    main()
